// ══════════════════════════════════════════════════════════════════
// MEDICONNECT AFRICA — Géographie africaine (React Native)
// 54 pays + 843 villes
// ══════════════════════════════════════════════════════════════════

export const PAYS_AFRIQUE = {
  "CI": { nom: "🇨🇮 Côte d'Ivoire",      code:"CI", indicatif:"+225", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "SN": { nom: "🇸🇳 Sénégal",            code:"SN", indicatif:"+221", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "BF": { nom: "🇧🇫 Burkina Faso",        code:"BF", indicatif:"+226", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "ML": { nom: "🇲🇱 Mali",               code:"ML", indicatif:"+223", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "GN": { nom: "🇬🇳 Guinée",             code:"GN", indicatif:"+224", monnaie:"GNF",  region:"Afrique de l'Ouest" },
  "TG": { nom: "🇹🇬 Togo",               code:"TG", indicatif:"+228", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "BJ": { nom: "🇧🇯 Bénin",              code:"BJ", indicatif:"+229", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "NE": { nom: "🇳🇪 Niger",              code:"NE", indicatif:"+227", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "NG": { nom: "🇳🇬 Nigéria",            code:"NG", indicatif:"+234", monnaie:"NGN",  region:"Afrique de l'Ouest" },
  "GH": { nom: "🇬🇭 Ghana",              code:"GH", indicatif:"+233", monnaie:"GHS",  region:"Afrique de l'Ouest" },
  "SL": { nom: "🇸🇱 Sierra Leone",       code:"SL", indicatif:"+232", monnaie:"SLL",  region:"Afrique de l'Ouest" },
  "LR": { nom: "🇱🇷 Libéria",           code:"LR", indicatif:"+231", monnaie:"LRD",  region:"Afrique de l'Ouest" },
  "MR": { nom: "🇲🇷 Mauritanie",         code:"MR", indicatif:"+222", monnaie:"MRU",  region:"Afrique de l'Ouest" },
  "GM": { nom: "🇬🇲 Gambie",            code:"GM", indicatif:"+220", monnaie:"GMD",  region:"Afrique de l'Ouest" },
  "GW": { nom: "🇬🇼 Guinée-Bissau",     code:"GW", indicatif:"+245", monnaie:"FCFA", region:"Afrique de l'Ouest" },
  "CV": { nom: "🇨🇻 Cap-Vert",          code:"CV", indicatif:"+238", monnaie:"CVE",  region:"Afrique de l'Ouest" },
  "CM": { nom: "🇨🇲 Cameroun",          code:"CM", indicatif:"+237", monnaie:"FCFA", region:"Afrique Centrale"   },
  "GA": { nom: "🇬🇦 Gabon",             code:"GA", indicatif:"+241", monnaie:"FCFA", region:"Afrique Centrale"   },
  "CD": { nom: "🇨🇩 RD Congo",          code:"CD", indicatif:"+243", monnaie:"CDF",  region:"Afrique Centrale"   },
  "CG": { nom: "🇨🇬 Congo-Brazzaville", code:"CG", indicatif:"+242", monnaie:"FCFA", region:"Afrique Centrale"   },
  "CF": { nom: "🇨🇫 Centrafrique",      code:"CF", indicatif:"+236", monnaie:"FCFA", region:"Afrique Centrale"   },
  "TD": { nom: "🇹🇩 Tchad",            code:"TD", indicatif:"+235", monnaie:"FCFA", region:"Afrique Centrale"   },
  "GQ": { nom: "🇬🇶 Guinée Équatoriale",code:"GQ", indicatif:"+240", monnaie:"FCFA", region:"Afrique Centrale"   },
  "ST": { nom: "🇸🇹 São Tomé-et-Príncipe",code:"ST",indicatif:"+239",monnaie:"STN",  region:"Afrique Centrale"   },
  "MA": { nom: "🇲🇦 Maroc",            code:"MA", indicatif:"+212", monnaie:"MAD",  region:"Afrique du Nord"    },
  "DZ": { nom: "🇩🇿 Algérie",          code:"DZ", indicatif:"+213", monnaie:"DZD",  region:"Afrique du Nord"    },
  "TN": { nom: "🇹🇳 Tunisie",          code:"TN", indicatif:"+216", monnaie:"TND",  region:"Afrique du Nord"    },
  "LY": { nom: "🇱🇾 Libye",           code:"LY", indicatif:"+218", monnaie:"LYD",  region:"Afrique du Nord"    },
  "EG": { nom: "🇪🇬 Égypte",          code:"EG", indicatif:"+20",  monnaie:"EGP",  region:"Afrique du Nord"    },
  "SD": { nom: "🇸🇩 Soudan",          code:"SD", indicatif:"+249", monnaie:"SDG",  region:"Afrique du Nord"    },
  "ET": { nom: "🇪🇹 Éthiopie",        code:"ET", indicatif:"+251", monnaie:"ETB",  region:"Afrique de l'Est"   },
  "KE": { nom: "🇰🇪 Kenya",           code:"KE", indicatif:"+254", monnaie:"KES",  region:"Afrique de l'Est"   },
  "TZ": { nom: "🇹🇿 Tanzanie",        code:"TZ", indicatif:"+255", monnaie:"TZS",  region:"Afrique de l'Est"   },
  "UG": { nom: "🇺🇬 Ouganda",         code:"UG", indicatif:"+256", monnaie:"UGX",  region:"Afrique de l'Est"   },
  "RW": { nom: "🇷🇼 Rwanda",          code:"RW", indicatif:"+250", monnaie:"RWF",  region:"Afrique de l'Est"   },
  "BI": { nom: "🇧🇮 Burundi",         code:"BI", indicatif:"+257", monnaie:"BIF",  region:"Afrique de l'Est"   },
  "SS": { nom: "🇸🇸 Soudan du Sud",   code:"SS", indicatif:"+211", monnaie:"SSP",  region:"Afrique de l'Est"   },
  "SO": { nom: "🇸🇴 Somalie",         code:"SO", indicatif:"+252", monnaie:"SOS",  region:"Afrique de l'Est"   },
  "DJ": { nom: "🇩🇯 Djibouti",       code:"DJ", indicatif:"+253", monnaie:"DJF",  region:"Afrique de l'Est"   },
  "ER": { nom: "🇪🇷 Érythrée",       code:"ER", indicatif:"+291", monnaie:"ERN",  region:"Afrique de l'Est"   },
  "MG": { nom: "🇲🇬 Madagascar",      code:"MG", indicatif:"+261", monnaie:"MGA",  region:"Afrique de l'Est"   },
  "MU": { nom: "🇲🇺 Maurice",         code:"MU", indicatif:"+230", monnaie:"MUR",  region:"Afrique de l'Est"   },
  "SC": { nom: "🇸🇨 Seychelles",      code:"SC", indicatif:"+248", monnaie:"SCR",  region:"Afrique de l'Est"   },
  "KM": { nom: "🇰🇲 Comores",        code:"KM", indicatif:"+269", monnaie:"KMF",  region:"Afrique de l'Est"   },
  "ZA": { nom: "🇿🇦 Afrique du Sud", code:"ZA", indicatif:"+27",  monnaie:"ZAR",  region:"Afrique Australe"   },
  "ZM": { nom: "🇿🇲 Zambie",         code:"ZM", indicatif:"+260", monnaie:"ZMW",  region:"Afrique Australe"   },
  "ZW": { nom: "🇿🇼 Zimbabwe",        code:"ZW", indicatif:"+263", monnaie:"ZWL",  region:"Afrique Australe"   },
  "MZ": { nom: "🇲🇿 Mozambique",      code:"MZ", indicatif:"+258", monnaie:"MZN",  region:"Afrique Australe"   },
  "MW": { nom: "🇲🇼 Malawi",          code:"MW", indicatif:"+265", monnaie:"MWK",  region:"Afrique Australe"   },
  "AO": { nom: "🇦🇴 Angola",         code:"AO", indicatif:"+244", monnaie:"AOA",  region:"Afrique Australe"   },
  "NA": { nom: "🇳🇦 Namibie",        code:"NA", indicatif:"+264", monnaie:"NAD",  region:"Afrique Australe"   },
  "BW": { nom: "🇧🇼 Botswana",       code:"BW", indicatif:"+267", monnaie:"BWP",  region:"Afrique Australe"   },
  "SZ": { nom: "🇸🇿 Eswatini",       code:"SZ", indicatif:"+268", monnaie:"SZL",  region:"Afrique Australe"   },
  "LS": { nom: "🇱🇸 Lesotho",        code:"LS", indicatif:"+266", monnaie:"LSL",  region:"Afrique Australe"   },
};

export const VILLES_PAR_PAYS = {
  "CI":["Abidjan","Yamoussoukro","Bouaké","Daloa","San-Pédro","Korhogo","Man","Gagnoa","Abengourou","Divo","Duekoué","Odienné","Bondoukou","Agboville","Grand-Bassam","Sassandra","Soubré","Séguéla","Ferkessédougou","Touba","Issia","Lakota","Bangolo","Bingerville","Grand-Lahou","Aboisso","Adzopé","Anyama","Tiassalé","Dimbokro"],
  "SN":["Dakar","Thiès","Kaolack","Ziguinchor","Saint-Louis","Touba","Mbour","Diourbel","Louga","Tambacounda","Kolda","Fatick","Sédhiou","Kaffrine","Matam","Kédougou","Pikine","Guédiawaye","Rufisque","Tivaouane","Mbacké"],
  "BF":["Ouagadougou","Bobo-Dioulasso","Koudougou","Ouahigouya","Banfora","Manga","Kaya","Fada N'Gourma","Tenkodogo","Dédougou","Kongoussi","Po","Réo","Gaoua","Diapaga","Titao","Tougan","Nouna","Dori","Ziniaré","Léo"],
  "ML":["Bamako","Sikasso","Mopti","Koutiala","Kayes","Ségou","Gao","Kidal","Tombouctou","Bougouni","Kati","San","Niono","Markala","Bla","Kolondiéba","Yorosso","Diéma","Nioro du Sahel","Douentza","Kita","Djenné"],
  "GN":["Conakry","Nzérékoré","Kindia","Kankan","Labé","Guéckédou","Mamou","Macenta","Faranah","Kissidougou","Dalaba","Pita","Siguiri","Kérouané","Beyla","Télimélé","Coyah","Dubréka","Forécariah","Fria"],
  "TG":["Lomé","Sokodé","Kara","Kpalimé","Atakpamé","Tsévié","Aného","Sotouboua","Mango","Bassar","Dapango","Notsé","Vogan","Tabligbo","Badou","Blitta","Tchamba","Kandé","Pagouda","Dapaong"],
  "BJ":["Cotonou","Porto-Novo","Djougou","Parakou","Lokossa","Ouidah","Abomey","Kandi","Natitingou","Bohicon","Malanville","Nikki","Save","Comé","Dassa-Zoumé","Tchaourou","Bassila","Banikoara","Abomey-Calavi","Sakété"],
  "NE":["Niamey","Zinder","Maradi","Agadez","Tahoua","Dosso","Diffa","Tillabéri","Arlit","Birni N'Konni","Tessaoua","Dakoro","Mirriah","Madarounfa","Mayahi","Gaya","Dogondoutchi","Filingué","Illéla"],
  "NG":["Lagos","Kano","Ibadan","Abuja","Port Harcourt","Benin City","Maiduguri","Zaria","Aba","Onitsha","Enugu","Kaduna","Ilorin","Warri","Jos","Abeokuta","Calabar","Owerri","Asaba","Uyo","Akure","Sokoto","Bauchi","Minna","Makurdi"],
  "GH":["Accra","Kumasi","Tamale","Sekondi-Takoradi","Ashaiman","Sunyani","Cape Coast","Koforidua","Tema","Obuasi","Techiman","Nkawkaw","Wa","Bolgatanga","Ho","Hohoe","Prestea","Tarkwa","Winneba","Berekum"],
  "SL":["Freetown","Bo","Kenema","Koidu","Makeni","Lunsar","Port Loko","Kabala","Magburaka","Kailahun","Bonthe","Moyamba","Pujehun","Kambia","Waterloo"],
  "LR":["Monrovia","Gbarnga","Kakata","Bensonville","Harper","Voinjama","Buchanan","Zwedru","Sanniquellie","Greenville","Tubmanburg","Robertsport","Ganta"],
  "MR":["Nouakchott","Nouadhibou","Rosso","Kaédi","Zouerate","Kiffa","Tidjikja","Atar","Sélibabi","Aleg","Akjoujt","Nema","Boutilimit","Aïoun el-Atrouss"],
  "GM":["Banjul","Serekunda","Brikama","Bakau","Farafenni","Lamin","Basse Santa Su","Kerewan","Mansa Konko","Janjanbureh","Bansang","Soma"],
  "GW":["Bissau","Bafatá","Gabú","Bissorã","Bolama","Cacheu","Catió","Mansôa","Bubaque","Farim","Buba"],
  "CV":["Praia","Mindelo","Santa Maria","Assomada","São Filipe","Espargos","Pedra Badejo","Tarrafal","Sal Rei","Ribeira Grande","Porto Novo"],
  "CM":["Yaoundé","Douala","Garoua","Bamenda","Maroua","Bafoussam","Ngaoundéré","Bertoua","Kumba","Loum","Nkongsamba","Dschang","Edéa","Kribi","Ebolowa","Foumban","Buea","Mbalmayo"],
  "GA":["Libreville","Port-Gentil","Franceville","Oyem","Moanda","Mouila","Lambaréné","Tchibanga","Koulamoutou","Makokou","Bitam","Gamba","Lastoursville"],
  "CD":["Kinshasa","Lubumbashi","Mbuji-Mayi","Kananga","Kisangani","Bukavu","Tshikapa","Kolwezi","Likasi","Bunia","Uvira","Goma","Matadi","Boma","Kikwit","Mbandaka","Kalemie","Butembo"],
  "CG":["Brazzaville","Pointe-Noire","Dolisie","Nkayi","Impfondo","Owando","Ouesso","Mossendjo","Madingou","Kinkala","Sibiti","Djambala","Gamboma","Makoua"],
  "CF":["Bangui","Bimbo","Mbaïki","Berberati","Kaga-Bandoro","Bambari","Bangassou","Bossangoa","Bria","Bouar","Carnot","Nola","Sibut"],
  "TD":["N'Djamena","Moundou","Sarh","Abéché","Kélo","Koumra","Pala","Am Timan","Bongor","Doba","Mongo","Ati","Faya-Largeau"],
  "GQ":["Malabo","Bata","Ebebiyín","Aconibe","Añisoc","Luba","Evinayong","Mongomo","Mbini"],
  "ST":["São Tomé","Trindade","Santana","Neves","Santo António"],
  "MA":["Casablanca","Rabat","Fès","Marrakech","Agadir","Tanger","Meknès","Oujda","Kenitra","Témara","Salé","Nador","Tétouan","Safi","El Jadida","Béni Mellal","Khouribga","Larache","Mohammedia","Settat"],
  "DZ":["Alger","Oran","Constantine","Annaba","Blida","Batna","Djelfa","Sétif","Sidi Bel Abbès","Biskra","Tébessa","El Oued","Skikda","Tiaret","Béjaïa","Tlemcen","Béchar","Mostaganem","Médéa","Ouargla","Ghardaïa","Tamanrasset"],
  "TN":["Tunis","Sfax","Sousse","Kairouan","Bizerte","Gabès","Ariana","Gafsa","La Marsa","Monastir","Ben Arous","Nabeul","Tataouine","Kasserine","Médenine","Djerba","Zarzis"],
  "LY":["Tripoli","Benghazi","Misrata","Tarhuna","Zawiya","Zliten","Al Khums","Ajdabiya","Derna","Sabha","Tobruk","Surt"],
  "EG":["Le Caire","Alexandrie","Gizeh","Suez","Louxor","Assouan","Ismaïlia","Fayoum","Zagazig","Asyout","Port-Saïd","Tanta","Mansourah","Hurghada","Charm el-Cheikh","Sohag","Qena","Minya","Damanhour"],
  "SD":["Khartoum","Omdurman","Khartoum Nord","Port Soudan","Kassala","El Obeid","Wad Medani","El Fasher","Atbara","Nyala","Gedaref","Kosti","Sennar","Dongola"],
  "ET":["Addis-Abeba","Dire Dawa","Mekele","Gondar","Awash","Adama","Jimma","Dessie","Bahir Dar","Shashamane","Bishoftu","Harar","Arba Minch","Hawassa","Nekemte"],
  "KE":["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Thika","Malindi","Kitale","Garissa","Nyeri","Meru","Embu","Kericho","Kisii","Naivasha","Machakos","Kakamega","Bungoma"],
  "TZ":["Dar es Salaam","Mwanza","Arusha","Moshi","Tanga","Dodoma","Morogoro","Zanzibar","Kigoma","Tabora","Mbeya","Musoma","Shinyanga","Iringa","Mtwara","Lindi","Sumbawanga"],
  "UG":["Kampala","Gulu","Lira","Mbarara","Jinja","Mbale","Mukono","Kasese","Masaka","Entebbe","Soroti","Kabale","Arua","Hoima","Tororo","Fort Portal","Masindi"],
  "RW":["Kigali","Butare","Gitarama","Ruhengeri","Gisenyi","Byumba","Cyangugu","Kibungo","Rwamagana","Nyanza","Kibuye","Musanze","Rubavu","Huye"],
  "BI":["Bujumbura","Gitega","Muyinga","Ngozi","Rumonge","Bururi","Kayanza","Mwaro","Cibitoke","Makamba","Bubanza","Kirundo"],
  "SS":["Juba","Malakal","Wau","Yei","Bor","Torit","Rumbek","Aweil","Bentiu","Kuajok","Nimule"],
  "SO":["Mogadiscio","Hargeisa","Bosasso","Berbera","Kismayo","Marka","Baidoa","Beledweyne","Galkayo"],
  "DJ":["Djibouti","Ali Sabieh","Dikhil","Tadjourah","Obock","Arta"],
  "ER":["Asmara","Keren","Massawa","Assab","Mendefera","Dekemhare","Barentu","Teseney"],
  "MG":["Antananarivo","Toamasina","Antsirabe","Fianarantsoa","Mahajanga","Toliara","Antsiranana","Ambovombe","Ambatondrazaka","Morondava","Manakara","Moramanga","Nosy Be","Sambava"],
  "MU":["Port-Louis","Beau Bassin-Rose Hill","Vacoas-Phoenix","Curepipe","Quatre Bornes","Triolet","Goodlands","Centre de Flacq","Mahébourg"],
  "SC":["Victoria","Anse Boileau","Beau Vallon","Bel Ombre","Cascade","Glacis"],
  "KM":["Moroni","Mutsamudu","Fomboni","Domoni","Tsémbéhou","Mitsamiouli"],
  "ZA":["Johannesburg","Le Cap","Durban","Pretoria","Port Elizabeth","Bloemfontein","Soweto","Pietermaritzburg","Benoni","Tembisa","East London","Vereeniging","Boksburg","Welkom","Newcastle","Midrand","Polokwane","Nelspruit"],
  "ZM":["Lusaka","Ndola","Kitwe","Kabwe","Chipata","Livingstone","Mufulira","Luanshya","Solwezi","Mansa","Kasama","Chingola","Mongu","Mazabuka","Kafue"],
  "ZW":["Harare","Bulawayo","Chitungwiza","Mutare","Gweru","Kwekwe","Kadoma","Masvingo","Chinhoyi","Norton","Marondera","Chegutu","Zvishavane","Hwange"],
  "MZ":["Maputo","Matola","Nampula","Beira","Chimoio","Nacala","Quelimane","Tete","Lichinga","Pemba","Inhambane","Xai-Xai","Maxixe","Mocuba","Cuamba"],
  "MW":["Lilongwe","Blantyre","Mzuzu","Zomba","Kasungu","Mangochi","Karonga","Salima","Nkhotakota","Nsanje","Balaka","Liwonde","Dedza","Mulanje"],
  "AO":["Luanda","Huambo","Lobito","Benguela","Kuito","Lubango","Malanje","Namibe","Soyo","Cabinda","Uíge","Saurimo","Menongue","Ndalatando","Caxito","Luena"],
  "NA":["Windhoek","Swakopmund","Rundu","Walvis Bay","Oshakati","Katima Mulilo","Gobabis","Keetmanshoop","Otjiwarongo","Tsumeb","Okahandja","Mariental","Rehoboth"],
  "BW":["Gaborone","Francistown","Molepolole","Selebi-Phikwe","Maun","Kanye","Serowe","Lobatse","Mahalapye","Palapye","Mogoditshane","Mochudi","Kasane"],
  "SZ":["Mbabane","Manzini","Lobamba","Big Bend","Malkerns","Nhlangano","Siteki","Piggs Peak"],
  "LS":["Maseru","Teyateyaneng","Mafeteng","Hlotse","Mohale's Hoek","Quthing","Qacha's Nek","Butha-Buthe"],
};

export const PAYS_LISTE = Object.values(PAYS_AFRIQUE)
  .sort((a, b) => a.nom.replace(/[^\w]/g,'').localeCompare(b.nom.replace(/[^\w]/g,'')));

export const getVillesByPays = (code) => VILLES_PAR_PAYS[code] || [];
export const getPaysInfo = (code) => PAYS_AFRIQUE[code] || null;
export const genererNumeroCarte  = (code, seq, annee = new Date().getFullYear()) =>
  `MC-${(code||'XX').toUpperCase()}-${annee}-${String(seq).padStart(6,'0')}`;
export const genererNumeroCompte = (code, seq, annee = new Date().getFullYear()) =>
  `MCA-${(code||'XX').toUpperCase()}-${annee}-${String(seq).padStart(6,'0')}`;

export default PAYS_AFRIQUE;
